apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
  namespace: gerald-env
  labels:
    app: ecommerce
spec:
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce 
    spec:
      containers:
      - name: ecommerce 
        image: geraldakenji/app-image:latest 
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
