apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service 
  namespace: gerald-env
spec:
  selector:
    app: ecommerce
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 32345
  type: NodePort
